name: CI Pipeline (TESTS, INFECTION)

on:
  pull_request:
    branches:
      - main

jobs:
  pest:
    name: Run Pest Tests on PHP 8.2, 8.3, and 8.4
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.2, 8.3, 8.4]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run Pest Tests
        run: ./vendor/bin/pest --colors --no-coverage

  infection:
    name: Run Mutation Testing (Infection) on PHP 8.2, 8.3, and 8.4
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.2, 8.3, 8.4]
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: xdebug
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run Infection (Mutation Testing)
        run: ./vendor/bin/infection --logger-github=true
